name: Reusable Deploy

on:
  workflow_call:
    inputs:
      artifact_name:
        description: Name of the build artifact
        required: false
        default: dist-files
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: dist

      - name: Output information
        run: echo "Deploying & uploading"